name: Release electron version

on:
  push:
    tags:
    - 'v*'

  workflow_dispatch:

env:
  DIST_TAG: preview

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Create Release 
        if: startsWith(matrix.os, 'ubuntu')
        # as electron-builder needs draft to upload artifacts, create once on linux
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build and Release
        run: npx quasar build -m electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
